config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'employee_signups#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'sessions/create', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :employee_signups
  resources :employees
  resources :employee_details
  resources :employee_attendances
  resources :employee_leaves
 
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true,
                    length: { minimum: 5 }
  validates :department, presence: true,
                    length: { minimum: 1}
  has_one :employee_detail
  has_many :employee_attendances
  has_many :employee_leaves
end

app/models/employee_attendance.rb
class EmployeeAttendance < ApplicationRecord
  belongs_to :employee
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
  belongs_to :employee
end

app/models/employee_leave.rb
class EmployeeLeave < ApplicationRecord
  belongs_to :employee
end

app/models/employee_signup.rb
class EmployeeSignup < ApplicationRecord
  has_secure_password

  validates :name, 
             presence: true
  validates :email,
             presence: true, 
             uniqueness:true, 
  format:{
             with:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
         }
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_employee, :employee_logged_in?

  def current_employee
    if session[:employee_signup_id]
    @employee_signup = EmployeeSignup.find(session[:employee_signup_id])
    end
  end

  def employee_logged_in?
   session[:employee_signup_id].present?
  end

    def check_employee_access?
      unless employee_logged_in?
        flash[:notice] = 'You cannot access this page.'
        redirect_to root_path
      end
    end
end

app/controllers/employee_attendances_controller.rb
class EmployeeAttendancesController < ApplicationController
     before_action :check_employee_access? 
  
  def index
    @employee = Employee.find(params[:employee_id])
    @employee_attendances = @employee.employee_attendances
  end

  def show
    @employee_attendance = EmployeeAttendance.find(params[:id])
  end

  def new
    @employee_attendance = EmployeeAttendance.new(employee_id: params[:employee_id])
  end

  def create
    @employee_attendance= EmployeeAttendance.new(employee_attendance_params)
    if @employee_attendance.save 
      redirect_to @employee_attendance  
    else 
      render 'new'
    end
  end

  private
  def employee_attendance_params
    params.require(:employee_attendance).permit(:employee_id, :status, :date)
  end
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController

  def show
    @employee_detail = EmployeeDetail.find(params[:id])
  end

  def new
    @employee_detail = EmployeeDetail.new(employee_id: params[:employee_id])
  end

  def edit
    @employee_detail = EmployeeDetail.find(params[:id])
  end

  def create
    @employee_detail = EmployeeDetail.new(employee_detail_params)
    if @employee_detail.save 
      redirect_to @employee_detail   
    else 
      render 'new'
    end
  end

  def update
    @employee_detail = EmployeeDetail.find(params[:id])  
    if @employee_detail.update(employee_detail_params)
      redirect_to @employee_detail
    else
      render 'edit'
    end
  end

  private
  def employee_detail_params
    params.require(:employee_detail).permit(:employee_id, :name, :photo, :age, :marriage_status, :state, :address )
    # params.permit(:name, :department)
  end
end

app/controllers/employee_leaves_controller.rb
  class EmployeeLeavesController < ApplicationController

    
    def new
       @employee_leave = EmployeeLeave.new(employee_id: params[:employee_id])
    end

    def create
       @employee_leave = EmployeeLeave.new(employee_leave_params)
        if @employee_leave.save 
         redirect_to @employee_leave  
    else 
      render 'new'
     end
  end

    private
       def employee_leave_params
       params.require(:employee_leave).permit(:employee_id, :leave_type, :start_date, :end_date, :description)
     end
  end

app/controllers/employee_signups_controller.rb
class EmployeeSignupsController < ApplicationController 

  def show
    @employee_signup = EmployeeSignup.find(params[:id])
  end

  def new
    @employee_signup = EmployeeSignup.new
  end

  def create
   @employee_signup = EmployeeSignup.new(employee_signup_params)
    if @employee_signup.save
        flash[:notice] = "You signed up successfully"
        redirect_to @employee_signup
    else
      flash[:notice] = "Form is invalid"
      render 'new'
    end
  end

  private
    def employee_signup_params
      params.require(:employee_signup).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
     @employee = Employee.find(params[:id])
  end

  def new
   @employee = Employee.new
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def create
    # render plain: params[:employee].inspect
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:success] = "successfull messages"
      redirect_to @employee   
    else 
       flash[:errors] = "give some input"
       redirect_to root_path  
      # render 'new'
    end
  end

  def update
  @employee = Employee.find(params[:id])
 
  if @employee.update(employee_params)
    redirect_to @employee
  else
    render 'edit'
  end
  end

 def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy
  redirect_to employees_path
 end

  private
  def employee_params
    params.require(:employee).permit(:name, :department)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @employee_signup = EmployeeSignup.find_by(email: params[:employee_signup][:email])
    if @employee_signup && @employee_signup.authenticate(params[:employee_signup][:password])
      session[:employee_signup_id] = @employee_signup.id 
      flash[:notice] = 'Login Successful'
      redirect_to new_employee_path
    else
      flash[:alert] = 'Invalid email and password'
      render :new 
    end
  end

  def destroy
    session[:employee_signup_id] = nil
    flash[:notice] = 'logout Successful'
    redirect_to root_path
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_attendances_helper.rb
module EmployeeAttendancesHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employee_leaves_helper.rb
module EmployeeLeavesHelper
end

app/helpers/employee_logins_helper.rb
module EmployeeLoginsHelper
end

app/helpers/employee_signups_helper.rb
module EmployeeSignupsHelper
end

app/helpers/employees_signup_helper.rb
module EmployeesSignupHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/employee_attendances/_form.html.erb
<%= form_with(model: @employee_attendance) do |form| %>
  <% if @employee_attendance.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee_attendance.errors.count, "error") %> prohibited
        this EmployeeAttendance from being saved:
      </h2>
      <ul>
        <% @employee_attendance.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :employee_id, value: @employee_attendance.employee_id %>
  <p>
    <%= form.label :status%><br/>
    <%= form.select :status, ['Present','Absent','HalfDay'] %>
  </p>

   <p>
    <%= form.label :date %><br/>
    <%= form.date_field :date %>
  </p>
  
  <%= form.submit %>    
 <% end %>

 

app/views/employee_attendances/index.html.erb
 <h1>List of Attendances</h1>
 
<table>
  <tr>
    <th>status</th>
    <th>date</th>
  </tr>
 
  <% @employee_attendances.each do |attendance| %>
    <tr>
      <td><%= attendance.status %></td>
      <td><%= attendance.date %></td> 
     </tr>
  <% end %>
</table> 

app/views/employee_attendances/new.html.erb
<h1>New Employee Attendance</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', employees_path %>

app/views/employee_attendances/show.html.erb
<p>
  <strong>Status:</strong>
  <%= @employee_attendance.status %>
</p>
 
<p>
  <strong>Date:</strong>
  <%= @employee_attendance.date %>
</p>

<%= link_to 'Back', employees_path %>

app/views/employee_details/_form.html.erb
<%= form_with(model: @employee_detail) do |form| %>
  <% if @employee_detail.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee_detail.errors.count, "error") %> prohibited
        this employeeDetail from being saved:
      </h2>
      <ul>
        <% @employee_detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :employee_id, value: @employee_detail.employee_id %>

  <p>
    <%= form.label :name %><br/>
    <%= form.text_field :name %>
  </p>
  
  <p>
    <%= form.label :photo %><br/>
    <%= form.file_field :photo %>
  </p>
  
  <p>
    <%= form.label :age %><br/>
    <%= form.text_field :age %>
  </p>   
  <p>
    <%= form.label :marriage_status %><br/>
    <%= form.select :marriage_status, ['Single','Married'] %>
  </p>

  <p>
    <%= form.label :state %><br/>
    <%= form.text_field :state %>
  </p>
     
  <p>
    <%= form.label :address %><br/>
    <%= form.text_area :address %>
  </p>
      
  <%= form.submit %>
      
 <% end %>

app/views/employee_details/edit.html.erb
<h1>Edit employeeDetails</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', employees_path %>

app/views/employee_details/index.html.erb
<!-- <h1>Listing of Employees</h1>
 
<table>
  <tr>
    <th>name</th>
    <th>photo</th>
    <th>age</th>
    <th>marriage_status</th>
    <th>state</th>
    <th>address</th>
  </tr>
 
  <% @employeeDetails.each do |employeeDetail| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employeeDetail.photo %></td>
      <td><%= employee.age %></td>
      <td><%= employee.marriage_status %></td>
      <td><%= employee.state %></td>
      <td><%= employee.address %></td>
      <td><%= link_to 'Show', employee_detail_path(employeeDetail) %></td><td></td><td></td>
       <td><%= link_to 'Edit', edit_employee_detail_path(employeeDetail) %></td><td>
    </tr>
  <% end %>
</table> -->

app/views/employee_details/new.html.erb
<h1>New Employee</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', employee_details_path %>

app/views/employee_details/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee_detail.name %>
</p>
 
<p>
  <strong>Photo:</strong>
  <%= @employee_detail.photo %>
</p>


<p>
  <strong>Age:</strong>
  <%= @employee_detail.age %>
</p>

<p>
  <strong>Marriage_status:</strong>
  <%= @employee_detail.marriage_status %>
</p>


<p>
  <strong>State:</strong>
  <%= @employee_detail.state %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee_detail.address %>
</p>

<%= link_to 'Edit', edit_employee_detail_path %>
<%= link_to 'Back', employees_path%>

app/views/employee_leaves/_form.html.erb
  <%= form_with(model: @employee_leave) do |form| %>
   <% if @employee_leave.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee_leave.errors.count, "error") %> prohibited
        this employeeleave from being saved:
      </h2>
      <ul>
        <% @employee_leave.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :employee_id, value: @employee_leave.employee_id %>
  <p>
    <%= form.label :leave_type %>
    <%= form.select :leave_type, ['PL','CL','SL','Other'] %>
  </p>
   <p>
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </p>

   <p>
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </p>

   <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>
  
  <%= form.submit %>    
 <% end %>

app/views/employee_leaves/new.html.erb
<h1>New leave Application<h1>

<%= render 'form' %>

<%= link_to 'Back', new_employee_path %>

app/views/employee_signups/_form.html.erb
<%= form_with(model: @employee_signup) do |form| %>

      <%= form.label :name %>
      <%= form.text_field :name %><br>

      <%= form.label :email %>
      <%= form.email_field :email %><br>

      <%= form.label :password %>
      <%= form.password_field :password %><br>

      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation %><br>

      <%= form.submit "Create my account" %>
      
 <% end %>

app/views/employee_signups/new.html.erb
<h1> LoginSignUp </h1>

<%= render 'form' %>

app/views/employee_signups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @employee_signup.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @employee_signup.email %>
</p>

<%= link_to 'Back', root_path %>

app/views/employees/_form.html.erb
<%= form_with(model: @employee) do |form| %>
 <% if @employee.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@employee.errors.count, "error") %> prohibited
         this employee from being saved:
       </h2>
       <ul>
         <% @employee.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
  <% end %>
  <table>    
   <tr>
    <td>
    <%= form.label :name %>
     </td>
      <td>
    <%= form.text_area :name %>
    </td>
    </tr>
  
    <tr>
      <td>
    <%= form.label :department %>
      </td>
       <td>
    <%= form.text_area :department %>
      </td>
    </tr>

    <tr>
      <td></td><td></td>
      <td>  
    <%= form.submit %>
      </td>
    </tr>

  </table>

<% end %>

app/views/employees/edit.html.erb
<h1>Edit employee</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
 <h1>Listing of Employees</h1>
 
<table>
  <tr>
    <th>name</th>
    <th>department</th>
  </tr>
 
  <% @employees.each do |employee| %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.department %></td>
      <td><%= link_to 'Show', employee_path(employee) %></td><td></td><td></td>
      <td><%= link_to 'Edit', edit_employee_path(employee) %></td><td></td><td></td>
      <td><%= link_to 'Destroy', employee_path(employee),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td>
        <% if employee.employee_detail %>
          <%= link_to 'Employee Detail', employee_detail_path(employee.employee_detail) %>
        <% else %>
          <%= link_to 'New Employee Detail', new_employee_detail_path(employee_id: employee.id) %>
        <% end %>
      
            <%= link_to 'Employee Attendances', employee_attendances_path(employee_id: employee.id) %>
             <%= link_to 'New Employee Attendance', new_employee_attendance_path(employee_id: employee.id) %>   
             <%= link_to 'New Leave Application', new_employee_leafe_path(employee_id: employee.id) %>  
        </td>
    </tr>
  <% end %>
</table> 

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>
<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
 

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>
 
<p>
  <strong>Department:</strong>
  <%= @employee.department %>
</p>

<%= link_to 'Back', employees_path %>